#!/usr/bin/env python3
"""Reproduce the embedded Field typefaces (fonttools 4.60.1, lv_font_conv 1.5.3).
Downloads are pinned and verified; normal firmware builds use the generated C.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import subprocess
from urllib.request import urlopen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

app = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--cache', type=Path, required=True)
parser.add_argument('--converter', type=Path, required=True)
args = parser.parse_args()
args.cache.mkdir(parents=True, exist_ok=True)
lock = json.loads((app / 'Fonts/sources.json').read_text())
for name, info in lock['files'].items():
    dest = args.cache / name
    if not dest.exists():
        dest.write_bytes(urlopen(info['url']).read())
    if hashlib.sha256(dest.read_bytes()).hexdigest() != info['sha256']:
        raise SystemExit(f'Checksum mismatch: {dest}')
for name, axes in [('NotoSansSC', {'wght':600}), ('Archivo', {'wght':600, 'wdth':85})]:
    font = instantiateVariableFont(TTFont(args.cache / (name+'.ttf')), axes, inplace=True)
    font.save(args.cache / (name+'-static.ttf'))
# GB2312 repertoire plus every literal used by the UI, without importing a bitmap font.
symbols = set()
for high in range(0xa1, 0xf8):
    for low in range(0xa1, 0xff):
        try: symbols.add(bytes([high,low]).decode('gb2312'))
        except UnicodeDecodeError: pass
symbols.update(c for p in app.glob('*.c') for c in p.read_text() if ord(c)>127)
symbols.add('\ufffd')
symbols = ''.join(sorted(c for c in symbols if ord(c)>127))
fonts = [('FlangeCjk24','NotoSansSC-static.ttf',24,None),
         ('FlangeSmall18','NotoSansSC-static.ttf',18,None),
         ('FlangeLabel14','Archivo-static.ttf',14,None),
         ('FlangeBody20','Archivo-static.ttf',20,None),
         ('FlangeTitle28','Archivo-static.ttf',28,None),
         ('FlangeMono14','IBMPlexMono.ttf',14,None),
         ('FlangeMono20','IBMPlexMono.ttf',20,None)]
for name, file, size, _ in fonts:
    dest = app / 'Fonts' / (name+'.c')
    command = [str(args.converter.resolve()), '--font',str(args.cache/file), '--size',str(size),
               '--bpp','4','--format','lvgl','--lv-include','FlangeView.h',
               '--lv-font-name',name,'-o',str(dest)]
    if name == 'FlangeCjk24':
        command += ['--symbols', symbols, '--lv-fallback','FlangeBody20']
    elif name == 'FlangeSmall18':
        ui_symbols = ''.join(sorted(set(c for p in app.glob('*.c') for c in p.read_text() if ord(c)>127)))
        command += ['--symbols',ui_symbols, '--lv-fallback','FlangeMono14']
    else: command += ['-r','0x20-0x7e']
    subprocess.run(command,check=True)
    # Avoid recording machine-specific cache locations and a huge command in the header.
    text = dest.read_text()
    text = re.sub(r' \* Opts:.*\n', ' * Generated by Tools/generate_font.py; see sources.json and OFL licenses.\n', text)
    dest.write_text('/* SPDX-License-Identifier: OFL-1.1 */\n' + text)
    print(dest.name, dest.stat().st_size)
