/** @file
  Definitions shared by the Platform Configuration driver and its formset.

  Included by the VFR too, so everything outside the VFRCOMPILE guard must be
  something VfrCompile can parse.

  Copyright (c) 2026, edk2-flange contributors.

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef PLATFORM_CONFIG_DXE_H_
#define PLATFORM_CONFIG_DXE_H_

#include <Guid/Qcs6490PlatformConfig.h>

//
// The one form of the Platform Configuration formset.
//
#define PLATFORM_CONFIG_FORM_ID  0x1000

#ifndef VFRCOMPILE

//
// The IFR of PlatformConfigHii.vfr and the strings of PlatformConfigHii.uni,
// generated by the build.
//
extern UINT8  PlatformConfigHiiBin[];
extern UINT8  Qcs6490PlatformConfigDxeStrings[];

#endif // VFRCOMPILE

#endif // PLATFORM_CONFIG_DXE_H_
