DSC_FILE=edk2-qualcomm/Platform/Thundercomm/RubikPi3/RubikPi3.dsc
PLATFORM_NAME=RubikPi3
FDF_FILE=edk2-qualcomm/Silicon/Qualcomm/QCS6490/QCS6490.fdf
FD_NAME=QCS6490_EFI
# Hash segment format XBL expects
MBN_VERSION=6
# uefi_a on UFS LUN 4: 1280 sectors of 4 KiB
UEFI_PARTITION_SIZE=0x500000
OUTPUT_NAME=RUBIKPI3_UEFI.elf
