PACKAGE_NAME="rubikpi3-msm"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^7[.]0[.]0-[0-9]+-generic$"
BUILD_EXCLUSIVE_ARCH="^aarch64$"
BUILD_EXCLUSIVE_CONFIG="CONFIG_ARM64 CONFIG_DRM_MSM"
MAKE[0]="'make' -j4 -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/drivers/gpu/drm/msm modules"
BUILT_MODULE_NAME[0]="msm"
BUILT_MODULE_LOCATION[0]="drivers/gpu/drm/msm"
DEST_MODULE_LOCATION[0]="/updates/dkms"
POST_INSTALL="refresh-initramfs $kernelver"
POST_REMOVE="refresh-initramfs $kernelver"
