#!/usr/bin/env python3
#
# Generate CjkFontGlyphs.c from a GNU Unifont BDF.
#
# The glyph set is GB 2312: its 6763 hanzi and 682 symbols cover Simplified
# Chinese menus as well as the device, volume and file names users tend to
# give their disks. Characters GraphicsConsoleDxe already draws from LaffStd
# are left out, so each code point has exactly one glyph in the database and
# which one wins never depends on the order the packages were registered in.
#
# Width follows CjkWidth.py rather than the glyph: the console lays text out
# by the \wide and \narrow markers and a terminal by East Asian Width, and a
# glyph that disagrees with both only smears into its neighbour. Unifont
# draws a handful of ambiguous-width symbols (circled and parenthesised
# numbers, stars) sixteen pixels wide; those are dropped.
#
# Usage:
#   GenCjkFontGlyphs.py --bdf unifont.bdf --edk2 <edk2 tree> -o CjkFontGlyphs.c
#
# Copyright (c) 2026, Eric Wu <eric3u@outlook.com>
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

import argparse
import os
import re
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from CjkWidth import is_wide  # noqa: E402

UNIFONT_ROWS = 16


def gb2312_chars():
    chars = []
    for hi in range(0xA1, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                chars.append(bytes([hi, lo]).decode('gb2312'))
            except UnicodeDecodeError:
                pass
    return chars


def parse_bdf(path):
    props = {}
    glyphs = {}
    cur = None
    bitmap = None
    with open(path, encoding='latin-1') as f:
        for line in f:
            line = line.strip()
            if cur is None and bitmap is None:
                m = re.match(r'(FONT_VERSION|COPYRIGHT)\s+"(.*)"$', line)
                if m:
                    props[m.group(1)] = m.group(2)
            if line.startswith('ENCODING '):
                cur = {'cp': int(line.split()[1])}
            elif line.startswith('BBX ') and cur is not None:
                cur['bbx'] = tuple(int(v) for v in line.split()[1:])
            elif line == 'BITMAP':
                bitmap = []
            elif line == 'ENDCHAR':
                cur['rows'] = bitmap
                glyphs[cur['cp']] = cur
                cur = None
                bitmap = None
            elif bitmap is not None:
                bitmap.append(line.strip())
    return props, glyphs


def laffstd_code_points(edk2):
    """Code points GraphicsConsoleDxe's built-in font already covers."""
    text_out = open(os.path.join(edk2, 'MdePkg/Include/Protocol/SimpleTextOut.h')).read()
    macros = {m.group(1): int(m.group(2), 16) for m in
              re.finditer(r'#define\s+(\w+)\s+0x([0-9a-fA-F]+)', text_out)}
    laff = open(os.path.join(edk2, 'MdeModulePkg/Universal/Console/GraphicsConsoleDxe/LaffStd.c')).read()
    cps = set()
    for m in re.finditer(r'^\s*\{\s*(?:\(CHAR16\))?(0x[0-9a-fA-F]+|\w+)\s*,', laff, re.M):
        token = m.group(1)
        cps.add(int(token, 16) if token.startswith('0x') else macros[token])
    return cps


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--bdf', required=True, help='GNU Unifont BDF (unifont.bdf)')
    ap.add_argument('--edk2', required=True, help='edk2 tree, for LaffStd.c and SimpleTextOut.h')
    ap.add_argument('-o', '--output', required=True)
    args = ap.parse_args()

    props, glyphs = parse_bdf(args.bdf)
    builtin = laffstd_code_points(args.edk2)

    narrow = []
    wide = []
    dropped = []
    for ch in gb2312_chars():
        cp = ord(ch)
        if cp in builtin:
            continue
        g = glyphs.get(cp)
        if g is None:
            sys.exit(f'U+{cp:04X} is in GB 2312 but not in {args.bdf}')
        width, height = g['bbx'][0], g['bbx'][1]
        if height != UNIFONT_ROWS or len(g['rows']) != UNIFONT_ROWS:
            sys.exit(f'U+{cp:04X}: expected {UNIFONT_ROWS} rows, BBX says {g["bbx"]}')
        if (width == 16) != is_wide(ch):
            dropped.append(ch)
            continue
        (wide if width == 16 else narrow).append((cp, ''.join(g['rows']).upper()))

    narrow.sort()
    wide.sort()

    if not props.get('FONT_VERSION') or not props.get('COPYRIGHT'):
        sys.exit(f'{args.bdf} carries no FONT_VERSION/COPYRIGHT')

    copyright_text = props['COPYRIGHT'].split(' License:')[0]

    out = []
    out.append('/** @file')
    out.append('')
    out.append('  GB 2312 glyphs for CjkFontDxe, in Unifont .hex bitmap order: one row')
    out.append('  per two (narrow) or four (wide) hex digits, sixteen rows, top first.')
    out.append('')
    out.append('  GENERATED by Tools/GenCjkFontGlyphs.py from GNU Unifont %s.' % props['FONT_VERSION'])
    out.append('  Do not edit; regenerate instead.')
    out.append('')
    out.append('  %d narrow and %d wide glyphs. Left out: characters LaffStd already' % (len(narrow), len(wide)))
    out.append('  draws, and ambiguous-width symbols Unifont draws wide:')
    out.append('  ' + ' '.join('U+%04X' % ord(c) for c in dropped[:8]))
    for i in range(8, len(dropped), 8):
        out.append('  ' + ' '.join('U+%04X' % ord(c) for c in dropped[i:i + 8]))
    out.append('')
    for line in re.findall(r'.{1,72}(?:\s|$)', copyright_text):
        out.append('  ' + line.strip())
    out.append('')
    out.append('  The glyph data is licensed under the SIL Open Font License, Version 1.1,')
    out.append('  see Unifont-OFL.txt.')
    out.append('')
    out.append('  SPDX-License-Identifier: OFL-1.1')
    out.append('')
    out.append('**/')
    out.append('')
    out.append('#include "CjkFontDxe.h"')
    out.append('')
    out.append('CONST CJK_NARROW_GLYPH_HEX  mCjkNarrowGlyphs[] = {')
    for cp, bits in narrow:
        out.append('  { 0x%04X, "%s" },' % (cp, bits))
    out.append('};')
    out.append('')
    out.append('CONST UINTN  mCjkNarrowGlyphCount = ARRAY_SIZE (mCjkNarrowGlyphs);')
    out.append('')
    out.append('CONST CJK_WIDE_GLYPH_HEX  mCjkWideGlyphs[] = {')
    for cp, bits in wide:
        out.append('  { 0x%04X, "%s" },' % (cp, bits))
    out.append('};')
    out.append('')
    out.append('CONST UINTN  mCjkWideGlyphCount = ARRAY_SIZE (mCjkWideGlyphs);')
    out.append('')

    with open(args.output, 'w', newline='\r\n') as f:
        f.write('\n'.join(out))

    print(f'{args.output}: {len(narrow)} narrow, {len(wide)} wide, {len(dropped)} dropped')


if __name__ == '__main__':
    main()
